version: 2

workflows:
  version: 2
  default:
    jobs:
      - build
      - release
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: mbgl/android-ndk-r19:8e91a7ebab
    environment:
      JVM_OPTS: -Xmx3200m
      BUILDTYPE: Debug
      IS_LOCAL_DEVELOPMENT: false
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Init submodules
          command: git submodule update --init --recursive
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run nitpick
          command: ./gradlew plugin-annotation:nitpick
      - run:
          name: Check Java code style
          command: make checkstyle
      - run:
          name: Run unit tests
          command: make test
      - run:
          name: Generate Activity Sanity tests
          command: make generate-sanity-test
      - run:
          name: Build testapp APK
          command: |
            ./gradlew accessToken
            ./gradlew app:assembleDebug
      - run:
          name: Build Test APK
          command: |
            ./gradlew app:assembleAndroidTest
      - run:
          name: Build release to test ProGuard rules
          command: ./gradlew app:assembleRelease
      - run:
          name: Log in to Google Cloud Platform
          command: |
            if [ -n "${GCLOUD_SERVICE_ACCOUNT_JSON}" ]; then
              echo "${GCLOUD_SERVICE_ACCOUNT_JSON}" > secret.json
              gcloud auth activate-service-account --key-file secret.json --project mapbox-plugins-android-4e407
              rm secret.json
            fi
      - run:
          name: Run instrumentation tests on Firebase
          no_output_timeout: 1200
          command: |
            if [ -n "${GCLOUD_SERVICE_ACCOUNT_JSON}" ]; then
              gcloud firebase test android models list
              gcloud firebase test android run --type instrumentation \
                --app app/build/outputs/apk/debug/app-debug.apk \
                --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
                --device-ids sailfish --os-version-ids 26 --locales en --orientations portrait --timeout 20m
            fi
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

# ------------------------------------------------------------------------------
  release:
    docker:
      - image: mbgl/android-ndk-r19:8e91a7ebab
    working_directory: ~/code
    environment:
      BUILDTYPE: Release
      IS_LOCAL_DEVELOPMENT: false
    steps:
      - checkout
      - run:
          name: Init submodules
          command: git submodule update --init --recursive
      - run:
          name: Generate Maven credentials
          shell: /bin/bash -euo pipefail
          command: |
            if [ -n "${PUBLISH_NEXUS_USERNAME}" ]; then
              aws s3 cp s3://mapbox/android/signing-credentials/secring.gpg secring.gpg
              echo "NEXUS_USERNAME=$PUBLISH_NEXUS_USERNAME
              NEXUS_PASSWORD=$PUBLISH_NEXUS_PASSWORD
              signing.keyId=$SIGNING_KEYID
              signing.password=$SIGNING_PASSWORD
              signing.secretKeyRingFile=../secring.gpg" >> gradle.properties
            fi
      - run:
          name: Build Plugins SDK
          command: make build-release
      - deploy:
          name: Publish Plugins SDK To Maven Central
          command: |
            if [ -n "${PUBLISH_NEXUS_USERNAME}" ]; then
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                make publish
              fi
            fi
      - store_artifacts:
          path: app/build/reports
          destination: reports
