package com.mapbox.pluginstylejson

object StyleJsonContants {
    val LAYER_BACKGROUND = "background"
    val LAYER_CYCLE = "cycle"
    val LAYER_CUSTOM = "custom"
    val LAYER_FILL_EXTRUSION = "fillextrusion"
    val LAYER_FILL = "fill"
    val LAYER_HEATMAP = "heatmap"
    val LAYER_HILLSHADE = "hillshade"
    val LAYER_LINE = "line"
    val LAYER_RASTER = "raster"
    val LAYER_SYMBOL = "symbol"
    val SOURCE_CUSTOM_GEOMETRY = "custom geometry"
    val SOURCE_GEO_JSON = "geojson"
    val SOURCE_IMAGE = "image"
    val SOURCE_RASTER_DEM = "rasterdem"
    val SOURCE_RASTER = "raster"
    val SOURCE_VECTOR = "vector"

    const val GEO_JSON_FEATURE = "Feature"
    const val GEO_JSON_FEATURE_COLLECTION = "FeatureCollection"
    const val GEO_JSON_GEOMETRY_COLLECTION = "GeometryCollection"
    const val GEO_JSON_LINE_STRING = "LineString"
    const val GEO_JSON_NULTI_LINE_STRING = "MultiLineString"
    const val GEO_JSON_MULTI_POINT = "MultiPoint"
    const val GEO_JSON_MULTI_POLYGON = "MultiPolygon"
    const val GEO_JSON_POINT = "Point"
    const val GEO_JSON_POLYGON = "Polygon"
}
